#!/usr/bin/env bash

rm stop

while [ 1 ]; do
    if [ -f stop ]; then
        exit 0
    fi

    ./src/driver-v5.sh
    if [ $? -eq 2 ]; then
        sleep 60
    fi
done

echo "... auto-tester exited."

