#!/usr/bin/env bash

while [ 1 ]; do
    if [ -f stop ]; then
        return
    fi

    #./src/driver.sh
    #if [ $? -eq 2 ]; then
        ./src/driver-pull.sh pull
        if [ $? -eq 2 ]; then
            sleep 60
        fi
    #fi
done
